# Generated by Django 6.0.4 on 2026-04-30 19:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_name', models.CharField(help_text='Unique identifier for the template', max_length=255, unique=True)),
                ('template_path', models.CharField(help_text='File path to the HTML template file (relative to templates directory)', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Description of what this template is used for', null=True)),
                ('input_variable_values', models.JSONField(blank=True, default=dict, help_text='Default/example dictionary of input variables for template rendering')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active and available for use')),
            ],
            options={
                'verbose_name': 'HTML Template',
                'verbose_name_plural': 'HTML Templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['template_name'], name='messaging_m_templat_ca7cba_idx'), models.Index(fields=['is_active'], name='messaging_m_is_acti_85d43d_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutBounds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_mail', models.EmailField(max_length=254)),
                ('is_sent', models.BooleanField(default=False)),
                ('body', models.TextField()),
                ('mail_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.mailtemplates')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
