# Generated by Django 6.0.4 on 2026-04-30 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('content', '0002_initial'),
        ('finance', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='common.transactionstatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='content.book'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.order'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.order'),
        ),
        migrations.AddField(
            model_name='payout',
            name='user',
            field=models.ForeignKey(help_text='Author', on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='promocodelog',
            name='promo_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='common.promocode'),
        ),
        migrations.AddField(
            model_name='promocodelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code_logs', to='users.userprofile'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['user', '-created_at'], name='finance_led_user_id_9472aa_idx'),
        ),
        migrations.AddIndex(
            model_name='ledger',
            index=models.Index(fields=['reference_type', 'reference_id'], name='finance_led_referen_396705_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='finance_ord_user_id_d99389_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['local_order_id'], name='finance_ord_local_o_944527_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway_payment_id'], name='finance_pay_gateway_741f4e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway_order_id'], name='finance_pay_gateway_b8538b_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['user', '-created_at'], name='finance_pay_user_id_6ee3c7_idx'),
        ),
        migrations.AddIndex(
            model_name='promocodelog',
            index=models.Index(fields=['user', '-used_at'], name='finance_pro_user_id_2c75d2_idx'),
        ),
    ]
