# Generated by Django 6.0.4 on 2026-05-17 15:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_bookpopularity_bookrecommendation'),
        ('finance', '0002_initial'),
        ('users', '0003_subscriptionorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorSalesMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(help_text='First day of the month (YYYY-MM-01)')),
                ('total_sales_count', models.IntegerField(default=0, help_text='Total units sold')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue from all books', max_digits=12)),
                ('book_count', models.IntegerField(default=0, help_text='Number of unique books sold')),
                ('total_views', models.IntegerField(default=0, help_text='Total page views')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_sales_metrics', to='users.userprofile')),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['author', '-month'], name='finance_aut_author__25e9c0_idx'), models.Index(fields=['-month'], name='finance_aut_month_7740a6_idx')],
                'unique_together': {('author', 'month')},
            },
        ),
        migrations.CreateModel(
            name='BookSalesMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(help_text='First day of the month (YYYY-MM-01)')),
                ('sales_count', models.IntegerField(default=0, help_text='Number of units sold')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue from sales', max_digits=12)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, help_text='Average rating for this month', max_digits=3, null=True)),
                ('views_count', models.IntegerField(default=0, help_text='Page views for this month')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_metrics', to='content.book')),
            ],
            options={
                'ordering': ['-month'],
                'indexes': [models.Index(fields=['book', '-month'], name='finance_boo_book_id_6ae028_idx'), models.Index(fields=['-month'], name='finance_boo_month_94cc38_idx')],
                'unique_together': {('book', 'month')},
            },
        ),
    ]
