# Generated by Django 6.0.4 on 2026-06-12 19:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_book_is_featured'),
        ('finance', '0003_authorsalesmetrics_booksalesmetrics'),
        ('users', '0004_bankdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Line item name', max_length=100)),
                ('amount_type', models.CharField(choices=[('%', 'Percentage'), ('INR', 'Fixed Amount (INR)')], max_length=10)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Base amount for % calculations', max_digits=12)),
                ('calculated_amount', models.DecimalField(decimal_places=2, help_text='Final calculated amount after % application', max_digits=12)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='users.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Charge name (e.g., Platform Fee, GST, Shipping)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Charge description')),
                ('amount_type', models.CharField(choices=[('%', 'Percentage'), ('INR', 'Fixed Amount (INR)')], help_text='% or INR', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount value (e.g., 5 for 5% or 200 for 200 INR)', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable charge application')),
                ('apply_to_order', models.BooleanField(default=True, help_text='Apply to book orders')),
                ('apply_to_subscription', models.BooleanField(default=True, help_text='Apply to subscriptions')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='finance_cha_is_acti_0f0c15_idx')],
            },
        ),
        migrations.CreateModel(
            name='BillLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('ORDER', 'Book Order'), ('SUBSCRIPTION', 'Subscription'), ('REFUND', 'Refund')], max_length=20)),
                ('reference_id', models.CharField(help_text='Order ID, Payment ID, or Subscription ID', max_length=100)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal before charges', max_digits=12)),
                ('breakdown_json', models.JSONField(default=dict, help_text='Complete breakdown with all charges applied')),
                ('total_charges', models.DecimalField(decimal_places=2, help_text='Sum of all charges', max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, help_text='Subtotal + total charges', max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_ledgers', to='users.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='finance_bil_user_id_d888a1_idx'), models.Index(fields=['reference_id'], name='finance_bil_referen_3db24b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1, help_text='Quantity of the book in cart')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='content.book')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.cart')),
            ],
            options={
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['cart', '-added_at'], name='finance_car_cart_id_005514_idx')],
                'unique_together': {('cart', 'book')},
            },
        ),
    ]
