# Generated by Django 6.0.4 on 2026-04-30 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('content', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_authored', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='common.language'),
        ),
        migrations.AddField(
            model_name='bookgenre',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres_relation', to='content.book'),
        ),
        migrations.AddField(
            model_name='bookgenre',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='common.genre'),
        ),
        migrations.AddField(
            model_name='booktag',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_relation', to='content.book'),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='content.category'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='content.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='content.subcategory'),
        ),
        migrations.AddField(
            model_name='booktag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='content.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='bookgenre',
            unique_together={('book', 'genre')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author', '-created_at'], name='content_boo_author__6d0fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['category'], name='content_boo_categor_986e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['is_checks_passed'], name='content_boo_is_chec_cdd249_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booktag',
            unique_together={('book', 'tag')},
        ),
    ]
