# Generated by Django 6.0.4 on 2026-05-17 15:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPopularity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(help_text='First day of the month (YYYY-MM-01)')),
                ('sales_count', models.IntegerField(default=0, help_text='Units sold this month')),
                ('view_count', models.IntegerField(default=0, help_text='Page views this month')),
                ('rating_count', models.IntegerField(default=0, help_text='Number of ratings')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, help_text='Average rating', max_digits=3)),
                ('popularity_score', models.DecimalField(decimal_places=2, default=0, help_text='Calculated popularity score (0-100)', max_digits=5)),
                ('rank', models.IntegerField(blank=True, help_text='Rank among all books for this month', null=True)),
                ('popularity_status', models.CharField(choices=[('trending', 'Trending'), ('popular', 'Popular'), ('moderate', 'Moderate'), ('new', 'New Release')], default='moderate', help_text='Status based on popularity', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popularity_metrics', to='content.book')),
            ],
            options={
                'ordering': ['-month', 'rank'],
                'indexes': [models.Index(fields=['book', '-month'], name='content_boo_book_id_661c1e_idx'), models.Index(fields=['-month', 'rank'], name='content_boo_month_c075fa_idx'), models.Index(fields=['popularity_status'], name='content_boo_popular_0d2bf5_idx')],
                'unique_together': {('book', 'month')},
            },
        ),
        migrations.CreateModel(
            name='BookRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation_type', models.CharField(choices=[('similar', 'Similar Books'), ('author', 'Other Books by Author'), ('genre', 'Same Genre'), ('trending', 'Trending Now'), ('curated', 'Curated Pick'), ('seasonal', 'Seasonal Recommendation'), ('custom', 'Custom Recommendation')], default='similar', help_text='Type of recommendation', max_length=50)),
                ('score', models.DecimalField(decimal_places=2, default=0.5, help_text='Recommendation score (0-1.0)', max_digits=5)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display recommendation')),
                ('reason', models.TextField(blank=True, help_text='Reason for recommendation', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this recommendation active?')),
                ('book', models.ForeignKey(help_text='Book being recommended from', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='content.book')),
                ('recommended_book', models.ForeignKey(help_text='Book being recommended to', on_delete=django.db.models.deletion.CASCADE, related_name='recommended_from', to='content.book')),
            ],
            options={
                'ordering': ['-score', 'display_order'],
                'indexes': [models.Index(fields=['book', '-score'], name='content_boo_book_id_49fcd5_idx'), models.Index(fields=['recommendation_type'], name='content_boo_recomme_b43b22_idx'), models.Index(fields=['is_active'], name='content_boo_is_acti_b4834a_idx')],
                'unique_together': {('book', 'recommended_book')},
            },
        ),
    ]
