# Generated by Django 6.0.4 on 2026-05-26 09:24

import apps.content.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_bookpopularity_bookrecommendation'),
        ('users', '0003_subscriptionorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='thumbnail_url',
            field=models.FileField(blank=True, help_text='Book thumbnail image', null=True, upload_to=apps.content.models.book_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image_url',
            field=models.FileField(help_text='Book cover image', upload_to=apps.content.models.book_cover_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='index_file_url',
            field=models.FileField(blank=True, help_text='Book index/TOC PDF', null=True, upload_to=apps.content.models.book_index_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='original_file_url',
            field=models.FileField(help_text='Original PDF file (< 20MB)', upload_to=apps.content.models.book_file_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='sample_read_url',
            field=models.FileField(blank=True, help_text='Sample PDF for preview', null=True, upload_to=apps.content.models.book_sample_path),
        ),
        migrations.CreateModel(
            name='BookUploadRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current status of the request', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When the book was submitted')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the request was reviewed', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)', null=True)),
                ('admin_comments', models.TextField(blank=True, help_text='Additional comments from admin', null=True)),
                ('author', models.ForeignKey(help_text='Author who uploaded the book', on_delete=django.db.models.deletion.CASCADE, related_name='book_upload_requests', to='users.userprofile')),
                ('book', models.OneToOneField(help_text='Reference to the uploaded book', on_delete=django.db.models.deletion.CASCADE, related_name='upload_request', to='content.book')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_upload_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='content_boo_status_5ce2a4_idx'), models.Index(fields=['author', 'status'], name='content_boo_author__3872d2_idx'), models.Index(fields=['reviewed_by', '-reviewed_at'], name='content_boo_reviewe_d22539_idx')],
            },
        ),
    ]
