# Generated by Django 6.0.4 on 2026-06-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_book_thumbnail_url_alter_book_cover_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Is this book featured?'),
        ),
    ]
