# Generated by Django 6.0.4 on 2026-05-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='features',
            field=models.TextField(null=True),
        ),
    ]
