# Generated by Django 6.0.4 on 2026-05-03 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedinka_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationtokens',
            name='token_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vedinka_auth.tokentypes'),
        ),
    ]
