# Generated by Django 6.0.4 on 2026-05-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedinka_auth', '0002_activationtokens_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentypes',
            name='token_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tokentypes',
            name='type_code',
            field=models.CharField(max_length=20),
        ),
    ]
