# Generated by Django 6.0.4 on 2026-05-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vedinka_auth', '0003_alter_tokentypes_token_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationtokens',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
