# Generated by Django 6.0.4 on 2026-04-30 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_initial'),
        ('storage', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlibrary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='userlibrarypwdbackup',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.book'),
        ),
        migrations.AddField(
            model_name='userlibrarypwdbackup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_pwd_backups', to='users.userprofile'),
        ),
        migrations.AddIndex(
            model_name='userlibrary',
            index=models.Index(fields=['user', '-purchased_at'], name='storage_use_user_id_f7dd66_idx'),
        ),
        migrations.AddIndex(
            model_name='userlibrary',
            index=models.Index(fields=['expiry_date'], name='storage_use_expiry__702b01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userlibrary',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='userlibrarypwdbackup',
            unique_together={('user', 'book')},
        ),
    ]
